spring.application.name=App
spring.datasource.url=jdbc:postgresql://localhost:5432/app
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_SENHA}
spring.datasource.driver-class-name=org.postgresql.Driver
hibernate.dialect=org.hibernate.dialect.HSQLDialect
spring.jpa.hibernate.ddl-auto=update
server.error.include-stacktrace=never
server.address=0.0.0.0
server.port=8080
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always